# Adapted from https://github.com/commercialhaskell/all-cabal-hashes-tool/blob/master/.travis.yml
# and http://anil.recoil.org/2013/09/30/travis-and-ocaml.html

# we use c for ocaml, stack automatically installs the correct GHC
language: c

# old, now that we use stack

#language: haskell
#sudo: false
# selected by stack for us - ignore
#env:
#  - GHCVER=7.8.4
#  - GHCVER=head

env:
  - OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.2
#  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.0.0
#  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
#  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.0.0
#  - OCAML_VERSION=4.00.1 OPAM_VERSION=1.1.0
#  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.0.0
#  - OCAML_VERSION=3.12.1 OPAM_VERSION=1.1.0
  
cache:
  directories:
  - $HOME/.stack
  
#matrix:
#  allow_failures:
#    - env: GHCVER=7.8.4
#    - env: GHCVER=head

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- chmod a+x ~/.local/bin/stack
- stack --no-terminal setup

install:
  # pre-build 'mwc-random' and 'SHA' as otherwise Travis CI sometimes runs out of memory
  - stack build mwc-random SHA -j 1
  - stack install

# build SAPIC
script:
  - bash -ex .travis-ci.sh

